### ISSUE TITLE
标题的格式问题

### ISSUE THREAD

**Issue by ZERO2ER0** [ChuandongXie/XAUATthesis#8]
您好，首先很感谢您一直在建设和维护这个模板，但我在使用过程中遇到一些问题。由于我明天就要答辩，如果您看到我的问题，很希望您拨冗帮助我解决这个格式问题。
1.  在新的模版中，所有一级标题中间没有空格，除了“摘要”，“目录”。
2.  所有标题在页眉中的显示是没有空格的，包括“摘要”，“目录”。
这个问题我实在是自己无法解决，方便的话可以加微信沟通吗。

**Comment by ChuandongXie** [comment]
好的，已添加好友。

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ZERO2ER0 ***@***.***>
Sent: Wednesday, June 5, 2024 1:44:50 PM
To: ChuandongXie/XAUATthesis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ChuandongXie/XAUATthesis] 标题的格式问题 (Issue #8)


您好，首先很感谢您一直在建设和维护这个模板，但我在使用过程中遇到一些问题。由于我明天就要答辩，如果您看到我的问题，很希望您拨冗帮助我解决这个格式问题。

  1.  在新的模版中，所有一级标题中间没有空格，除了“摘要”。
  2.  所有标题在页眉中的显示是没有空格的，包括“摘要”。
这个问题我实在是自己无法解决，方便的话可以加微信沟通吗。我的微信是 13227759887.

―

**Comment by ChuandongXie** [comment]
“摘要”、“目录”空格问题可在cls文件中修改，另已更新参考文献行距 90926da9888ba60a10dcd0a05da72a7f26c6353d
