### ISSUE TITLE
参考文献引用与打印的问题

### ISSUE THREAD

**Issue by yangyang9912** [ChuandongXie/XAUATthesis#9]
非常感谢您提供这一latex模板，想请问一下您我在编译的时候无法正常打印参考文献，这是否是项目本身的问题？

**Comment by ChuandongXie** [comment]
@jinyang06 感谢提供的讯息。我刚在一台全新的电脑试了用MiKTeX编译了一下，是能够正常打印参考文献的。这份模板的编译顺序是'XeLaTeX-Biber-XeLaTeX-XeLaTeX'，您可以再试一下。

**Comment by yangyang9912** [comment]
> @jinyang06 感谢提供的讯息。我刚在一台全新的电脑试了用MiKTeX编译了一下，是能够正常打印参考文献的。这份模板的编译顺序是'XaLaTeX-Biber-XaLaTeX-XaLaTeX'，您可以再试一下。

感谢您的回复，根据您的提示，已经解决这一问题，非常感谢您提供的帮助！

**Comment by ChuandongXie** [comment]
@jinyang06 感谢反馈。另我刚更新了在线编译平台网址 [#40d0729](https://github.com/ChuandongXie/XAUATthesis/commit/40d0729deefe81d1b2cb451defbc36dd28580944)，有需要也可以用线上平台编译。不过线上平台版本更新可能不及时，以Github版本为准。
